version: "3.3"
services:
  link-shortener:
    build: .
    environment:
      LS_DASHBOARD_SUBDOMAIN: dashboard
      LS_DASHBOARD_ADMIN_USERNAME: admin
      LS_DASHBOARD_SHOWPORT: "false"
      LS_SERVER_HOSTNAME: hostname
      LS_SERVER_PORT: 9000
      LS_DATABASE_PATH: "/data/url-database.db"
    volumes:
      - ${PWD}/data:/data
